### PR TITLE
Add Denmark to list of regions processed 

### PR DESCRIPTION
**Pull request by KasperFranz**
I have executed this locally on my machine. Some of it is still running, but we should be able to get it down to 0 or close to that

### CODE REVIEW

**Comment by matkoniecz** [comment]
in such case I would also

- remove it from https://github.com/matkoniecz/OSM-wikipedia-tag-validator/blob/master/countries_not_processed.yml
- put link to this PR in `requested_by` field

**Comment by KasperFranz** [comment]
Will get that added now

**Comment by matkoniecz** [comment]
oh, and feel free to bump `priority_multiplier` to say 7 (the same for London) if you are planning to review this entries (can be done as a separate PR)

main effect is that results in more frequent rerun of updates and is intended to (1) give actually used data more frequent updates (2) reduce requests for manual data refreshes

**Comment by KasperFranz** [comment]
> oh, and feel free to bump `priority_multiplier` to say 7 (the same for London) if you are planning to review this entries (can be done as a separate PR)
> 
> main effect is that results in more frequent rerun of updates and is intended to (1) give actually used data more frequent updates (2) reduce requests for manual data refreshes

Interesting,

How is the update working right now? is it a manual process or is there a process for it?

**Comment by matkoniecz** [comment]
> How is the update working right now? is it a manual process or is there a process for it?

https://github.com/matkoniecz/OSM-wikipedia-tag-validator/blob/master/script.py is run on my personal laptop with cache configured to be on hard drive so it is not eating through SSD lifetime, and outdated backup drive is being used instead

I though about putting it on some proper server at some point, but for now I am working rather on processing false positives, making bot edits, integrating with MR etc (there is still more found errors than people processing them...)

**Comment by KasperFranz** [comment]
> > How is the update working right now? is it a manual process or is there a process for it?
> 
> https://github.com/matkoniecz/OSM-wikipedia-tag-validator/blob/master/script.py is run on my personal laptop with cache configured to be on hard drive so it is not eating through SSD lifetime, and outdated backup drive is being used instead
> 
> I though about putting it on some proper server at some point, but for now I am working rather on processing false positives, making bot edits, integrating with MR etc (there is still more found errors than people processing them...)

That sounds like a good plan, 
How long does the process take to update them all? 
For Denmark I had it running for a few hours

**Comment by KasperFranz** [comment]
Let me know if there is anything I can support with

**Comment by matkoniecz** [comment]
https://github.com/matkoniecz/wikibrain/issues/2

**Comment by matkoniecz** [comment]
potential PRs like https://github.com/matkoniecz/wikibrain/commit/8c0a7af0e6830dcb79c23eddb1fb5b0f12144c1e for detecting, reporting and hiding Wikidata false positives (with optional reporting then at https://www.wikidata.org/wiki/User:Mateusz_Konieczny/failing_testcases ) would be also welcome

**Pull request merged**
