### PR TITLE
Add YAML as requirement

### PR DESCRIPTION
**Pull request by KasperFranz**
When trying to install this on my local I ran into this issue (on top of the wikidata one)

### CODE REVIEW

**Comment by matkoniecz** [comment]
which wikidata issue?

**Comment by matkoniecz** [comment]
And thanks for sending PR! I admit that this code is not well tested for reusability and PRs fixing this are highly welcome! Or issues if someone is stuck.

(and yes, caching method for wikipedia/wikidata calls is half hilarious half broken and half just sad, likely it should be replaced by some library or at least a propoer database)

**Comment by KasperFranz** [comment]
With wikidata issues I was referring to the requirements.

Do you have a list of issues you want to get resolved? maybe we could create issues and tackle them as we go?

**Comment by matkoniecz** [comment]
> With wikidata issues I was referring to the requirements.

sadly, I am still confused

do you mean wikibrain mentioned in https://github.com/matkoniecz/OSM-wikipedia-tag-validator#dependencies ?

**Comment by matkoniecz** [comment]
if yes then finding good way to provide global configuration and migrating to it would be useful ( see https://github.com/matkoniecz/wikibrain#installation )

honestly I have no good idea - my idea with special package was silly, environmental variables seems ugly, centralized config file feels bad somehow... Not sure what would be the best solution and why (and I admit that code for me works as is and I put too much effort into this project so I made no progress on that field, latest bigger work for publishing PR tasks as requested by some and some bot edits)

**Comment by matkoniecz** [comment]
but if you are interested in making config saner: feel free to propose some solution and describe why it makes sense

**Comment by KasperFranz** [comment]
I got it to work in the end, but I had a few issues running it because of wikibrains and the global config required.


getting something to work is always the first step and then optimizations can come if required and if it makes sense

**Comment by matkoniecz** [comment]
BTW, I pushed some commits at https://github.com/matkoniecz/wikibrain/commits/master/ that eliminate some wikidata false positives

**Pull request merged**
